create table if not exists public.app_messages (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_name text not null default '系统',
  sender_avatar_path text,
  type text not null default 'info',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint app_messages_type_check check (type in ('info', 'success', 'error'))
);

create index if not exists app_messages_recipient_created_at_idx
  on public.app_messages(recipient_id, created_at desc);

alter table public.app_messages enable row level security;

drop policy if exists "Users can read their own app messages" on public.app_messages;
create policy "Users can read their own app messages"
  on public.app_messages
  for select
  using (auth.uid() = recipient_id);

drop policy if exists "Users can update their own app messages" on public.app_messages;
create policy "Users can update their own app messages"
  on public.app_messages
  for update
  using (auth.uid() = recipient_id)
  with check (auth.uid() = recipient_id);

create table if not exists public.vocabulary_change_requests (
  id bigint generated by default as identity primary key,
  vocabulary_id bigint references public.vocabulary(id) on delete set null,
  set_id bigint not null references public.vocabulary_sets(id) on delete cascade,
  requester_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  original_data jsonb not null default '{}'::jsonb,
  changes jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  constraint vocabulary_change_requests_action_check check (action in ('update', 'delete')),
  constraint vocabulary_change_requests_status_check check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists vocabulary_change_requests_set_created_at_idx
  on public.vocabulary_change_requests(set_id, created_at desc);

alter table public.vocabulary_change_requests enable row level security;

drop policy if exists "Users can read their own vocabulary requests" on public.vocabulary_change_requests;
create policy "Users can read their own vocabulary requests"
  on public.vocabulary_change_requests
  for select
  using (
    auth.uid() = requester_id
    or exists (
      select 1
      from public.set_members manager
      where manager.set_id = vocabulary_change_requests.set_id
        and manager.user_id = auth.uid()
        and manager.role in ('owner', 'admin')
    )
  );

create or replace function public.request_vocabulary_item_change(
  p_vocabulary_id bigint,
  p_action text,
  p_changes jsonb default '{}'::jsonb
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  target_set_id bigint;
  target_set_name text;
  target_word text;
  target_reading text;
  target_pitch integer;
  target_meaning text;
  target_contributor_name text;
  requester_name text;
  requester_avatar_path text;
  original_snapshot jsonb;
  request_id bigint;
  message_content text;
begin
  if current_user_id is null then
    return 'not_authenticated';
  end if;

  if p_action not in ('update', 'delete') then
    return 'invalid_action';
  end if;

  select
    vocabulary.set_id,
    vocabulary_sets.name,
    vocabulary.word,
    vocabulary.reading,
    vocabulary.pitch,
    vocabulary.meaning,
    vocabulary.contributor_name
    into
      target_set_id,
      target_set_name,
      target_word,
      target_reading,
      target_pitch,
      target_meaning,
      target_contributor_name
  from public.vocabulary
  join public.vocabulary_sets on vocabulary_sets.id = vocabulary.set_id
  where vocabulary.id = p_vocabulary_id;

  if not found then
    return 'not_found';
  end if;

  if exists (
    select 1
    from public.set_members
    where set_id = target_set_id
      and user_id = current_user_id
      and (
        role = 'owner'
        or (role = 'admin' and can_edit_phrases = true)
      )
  ) then
    return 'already_allowed';
  end if;

  if not exists (
    select 1
    from public.set_members
    where set_id = target_set_id
      and user_id = current_user_id
  ) then
    return 'forbidden';
  end if;

  select
    coalesce(nullif(display_name, ''), nullif(email, ''), '用户'),
    avatar_path
    into requester_name, requester_avatar_path
  from public.user_profiles
  where user_id = current_user_id;

  requester_name := coalesce(requester_name, '用户');
  original_snapshot := jsonb_build_object(
    'set_name', target_set_name,
    'word', target_word,
    'reading', target_reading,
    'pitch', target_pitch,
    'meaning', target_meaning,
    'contributor_name', target_contributor_name
  );

  insert into public.vocabulary_change_requests (
    vocabulary_id,
    set_id,
    requester_id,
    action,
    original_data,
    changes
  )
  values (
    p_vocabulary_id,
    target_set_id,
    current_user_id,
    p_action,
    original_snapshot,
    coalesce(p_changes, '{}'::jsonb)
  )
  returning id into request_id;

  message_content :=
    requester_name
    || case when p_action = 'delete' then ' 请求删除词汇集「' else ' 请求修改词汇集「' end
    || coalesce(target_set_name, '未命名词汇集')
    || '」中的词条「'
    || coalesce(target_word, '未命名词条')
    || '」。';

  insert into public.app_messages (
    recipient_id,
    sender_id,
    sender_name,
    sender_avatar_path,
    type,
    content,
    metadata
  )
  select
    member.user_id,
    current_user_id,
    requester_name,
    requester_avatar_path,
    'info',
    message_content,
    jsonb_build_object(
      'kind', 'vocabulary_change_request',
      'request_id', request_id,
      'vocabulary_id', p_vocabulary_id,
      'set_id', target_set_id,
      'set_name', target_set_name,
      'action', p_action,
      'status', 'pending',
      'original', original_snapshot,
      'changes', coalesce(p_changes, '{}'::jsonb)
    )
  from public.set_members member
  where member.set_id = target_set_id
    and member.user_id <> current_user_id
    and (
      member.role = 'owner'
      or (member.role = 'admin' and member.can_edit_phrases = true)
    );

  return 'ok';
end;
$$;

create or replace function public.resolve_vocabulary_change_request(
  p_request_id bigint,
  p_resolution text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  request_record public.vocabulary_change_requests%rowtype;
  resolver_name text;
  resolver_avatar_path text;
  target_word text;
  result_content text;
  result_type text;
begin
  if current_user_id is null then
    return 'not_authenticated';
  end if;

  if p_resolution not in ('approved', 'rejected') then
    return 'invalid_resolution';
  end if;

  select *
    into request_record
  from public.vocabulary_change_requests
  where id = p_request_id
  for update;

  if not found then
    return 'not_found';
  end if;

  if request_record.status <> 'pending' then
    return 'already_resolved';
  end if;

  if not exists (
    select 1
    from public.set_members
    where set_id = request_record.set_id
      and user_id = current_user_id
      and (
        role = 'owner'
        or (role = 'admin' and can_edit_phrases = true)
      )
  ) then
    return 'forbidden';
  end if;

  target_word := coalesce(request_record.original_data ->> 'word', '未命名词条');

  if p_resolution = 'approved' then
    if request_record.action = 'delete' then
      delete from public.vocabulary
      where id = request_record.vocabulary_id;
    else
      update public.vocabulary
      set
        word = coalesce(nullif(trim(request_record.changes ->> 'word'), ''), word),
        reading = coalesce(nullif(trim(request_record.changes ->> 'reading'), ''), reading),
        pitch = case
          when request_record.changes ? 'pitch'
            then nullif(request_record.changes ->> 'pitch', '')::integer
          else pitch
        end,
        meaning = coalesce(nullif(trim(request_record.changes ->> 'meaning'), ''), meaning),
        contributor_name = coalesce(
          nullif(trim(request_record.changes ->> 'contributor_name'), ''),
          contributor_name
        )
      where id = request_record.vocabulary_id;

      if not found then
        return 'not_found';
      end if;
    end if;
  end if;

  update public.vocabulary_change_requests
  set
    status = p_resolution,
    resolved_at = now(),
    resolved_by = current_user_id
  where id = p_request_id;

  update public.app_messages
  set metadata = jsonb_set(metadata, '{status}', to_jsonb(p_resolution))
  where metadata ->> 'kind' = 'vocabulary_change_request'
    and (metadata ->> 'request_id')::bigint = p_request_id;

  select
    coalesce(nullif(display_name, ''), nullif(email, ''), '管理员'),
    avatar_path
    into resolver_name, resolver_avatar_path
  from public.user_profiles
  where user_id = current_user_id;

  resolver_name := coalesce(resolver_name, '管理员');
  result_type := case when p_resolution = 'approved' then 'success' else 'error' end;
  result_content :=
    '你关于词条「'
    || target_word
    || '」的'
    || case when request_record.action = 'delete' then '删除' else '修改' end
    || '申请已'
    || case when p_resolution = 'approved' then '通过。' else '被拒绝。' end;

  insert into public.app_messages (
    recipient_id,
    sender_id,
    sender_name,
    sender_avatar_path,
    type,
    content,
    metadata
  )
  values (
    request_record.requester_id,
    current_user_id,
    resolver_name,
    resolver_avatar_path,
    result_type,
    result_content,
    jsonb_build_object(
      'kind', 'vocabulary_change_request_result',
      'request_id', p_request_id,
      'resolution', p_resolution,
      'action', request_record.action,
      'vocabulary_id', request_record.vocabulary_id,
      'set_id', request_record.set_id
    )
  );

  return 'ok';
end;
$$;
